package outputModules.csv.exporters;

import java.util.Map;

import cfg.CFG;
import cfg.CFGEdge;
import cfg.nodes.ASTNodeContainer;
import cfg.nodes.AbstractCFGNode;
import cfg.nodes.CFGEntryNode;
import cfg.nodes.CFGExceptionNode;
import cfg.nodes.CFGExitNode;
import cfg.nodes.CFGNode;
import databaseNodes.EdgeTypes;
import databaseNodes.NodeKeys;
import misc.MultiHashMap;
import outputModules.common.CFGExporter;
import outputModules.common.Writer;

public class CSVCFGExporter extends CFGExporter
{
	
	public static MultiHashMap<Long, Long> cfgSave = new MultiHashMap<Long, Long>();

	@Override
	protected void writeCFGNode(CFGNode statement,
			Map<String, Object> properties)
	{
		properties.put(NodeKeys.FUNCTION_ID,
				String.format("%d", Writer.getIdForObject(currentFunction)));
		Writer.addNode(statement, properties);
	}

	@Override
	protected void addFlowToLink(Object srcBlock, Object dstBlock,
			Map<String, Object> properties)
	{
		long srcId = Writer.getIdForObject(srcBlock);
		long dstId = Writer.getIdForObject(dstBlock);
		Writer.addEdge(srcId, dstId, properties, EdgeTypes.FLOWS_TO);
	}

	/**
	 * Simple method that takes a CFG and writes out the edges.
	 */
	public void writeCFGEdges(CFG cfg) {

		for( CFGEdge cfgEdge : cfg.getEdges())	{

			CFGNode src = cfgEdge.getSource();
			CFGNode dst = cfgEdge.getDestination();

			// skip blocks that are neither entry, exit nor AST nodes
			// (e.g., artificial [ERROR] blocks and such generated by the CFG factory)
			if( exportable(src) && exportable(dst)) {
				emitEdge(src, dst);
			}
		}

		// Artificial CFGExceptionNodes (try -> exception -> catch) are not AST/entry/exit nodes, so
		// every edge touching them is dropped by the filter above. That orphans catch blocks: their
		// statements never appear in cfgSave and are never analyzed (taint sinks in error handlers
		// become invisible). Bypass the exception node by linking each of its AST predecessors
		// directly to each of its AST successors, so catch (and finally-after-catch) bodies stay
		// reachable. This is the sound over-approximation: any statement in the try may throw.
		for( CFGNode v : cfg.getVertices()) {
			if( !(v instanceof CFGExceptionNode)) continue;
			for( CFGEdge in : cfg.incomingEdges(v)) {
				CFGNode p = in.getSource();
				if( !exportable(p)) continue;
				for( CFGEdge out : cfg.outgoingEdges(v)) {
					CFGNode s = out.getDestination();
					if( !exportable(s)) continue;
					emitEdge(p, s);
				}
			}
		}
		// clean up
		Writer.reset();
	}

	private boolean exportable(CFGNode n) {
		return n instanceof ASTNodeContainer || n instanceof CFGEntryNode || n instanceof CFGExitNode;
	}

	private void emitEdge(CFGNode src, CFGNode dst) {
		// CFG nodes that are AST node containers have their ids stored in their AST node;
		// abstract nodes such as entry or exit nodes have their id set internally.
		Long srcId = (src instanceof ASTNodeContainer) ? ((ASTNodeContainer)src).getASTNode().getNodeId()
				: ((AbstractCFGNode)src).getNodeId();
		Long dstId = (dst instanceof ASTNodeContainer) ? ((ASTNodeContainer)dst).getASTNode().getNodeId()
				: ((AbstractCFGNode)dst).getNodeId();

		if( cfgSave.containsKey(srcId) && cfgSave.get(srcId).contains(dstId))
			return;   // avoid duplicate edges (would inflate the merge in-degree Edgesize)

		cfgSave.add(srcId, dstId);

		Writer.setIdForObject(src, srcId);
		Writer.setIdForObject(dst, dstId);
		addFlowToLink( src, dst, null);
	}
	
}
